# AZFW0002: Avoid async void

| | Value |
|-|-|
| **Rule ID** |AZFW0002|
| **Category** |[Usage]|
| **Severity** |Error|


## Cause

This rule is triggered when an async method uses `void` as return type.

## Rule description

When an exception is thrown out of an `async Task` or `async Task<T>` method, that exception is captured and placed on the `Task` object. With `async void` methods, there is no `Task` object, so any exceptions thrown out of an async void method will be posted to thread pool. An unhandled exception on the thread pool will cause the whole process to terminate.

Please refer [Avoid Async Void section in Best Practices in Asynchronous Programming](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#avoid-async-void) for more info.

## How to fix violations

To fix violations, change the method return type from `async void` to `async Task`

Sample code with violation, before the fix

    [Function("Function1")]
    public static async void Run([QueueTrigger("myqueue-items",
                                  Connection = "connstr")] string myQueueItem,
        FunctionContext context)
    {
        await Task.Delay(1);
        var logger = context.GetLogger("Function1");
        logger.LogInformation($"Queue trigger function processed: {myQueueItem}");
    }

Sample code, after the fix

    [Function("Function1")]
    public static async Task Run([QueueTrigger("myqueue-items",
                                  Connection = "connstr")] string myQueueItem,
        FunctionContext context)
    {
        await Task.Delay(1);
        var logger = context.GetLogger("Function1");
        logger.LogInformation($"Queue trigger function processed: {myQueueItem}");
    }


## When to suppress warnings

This rule should not be suppressed, as the an exception thrown from the async void method would cause the application process to crash.
